workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^topic\/.*/ && $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always

stages:
  - check
  - test

.check:
  stage: check
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/tryton/ci

check-doc:
  extends: .check
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/sphinxdoc/sphinx
  cache:
    paths:
      - .cache/pip
  before_script:
    - pip install -r doc/requirements-doc.txt
    - pip install sphinx-lint rstcheck[sphinx]
  script:
    - python -m sphinx -T -E -W -n -b html doc _build/html
    - python -m sphinxlint doc
    - rstcheck --recursive doc
    - python -m sphinx -T -E -W -n -b linkcheck doc _build
  rules:
    - changes:
        - doc/**/*

check-flake8:
  extends: .check
  script:
    - flake8

check-isort:
  extends: .check
  script:
    - isort -m VERTICAL_GRID -c .

check-dist:
  extends: .check
  before_script:
    - pip install twine
  script:
    - python setup.py sdist
    - twine check dist/*

.test:
  stage: test

.test-tox:
  extends: .test
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  before_script:
    - pip install tox
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

test-tox-python:
  extends: .test-tox
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:${PYTHON_VERSION}
  script:
    - tox -e "py${PYTHON_VERSION/./}" -- -v --output-file junit.xml
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

test-tox-pypy:
  extends: .test-tox
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/pypy:3
  script:
    - tox -e pypy3 -- -v --output-file junit.xml
