[tox]
envlist = py39, py310, py311, py312, py313, py314, pypy3

[testenv]
changedir = {toxworkdir}
extras = fodt
commands =
    coverage run --source=relatorio --omit=*/tests/* -m xmlrunner discover -s relatorio.tests {posargs}
commands_post =
    coverage report
    coverage xml
deps =
    coverage
    unittest-xml-reporting
    pyyaml
    pycha
passenv = *
