[tox]
envlist = py39, py310, py311, py312, py313, py314, pypy3

[testenv]
changedir = {env_site_packages_dir}
extras = fodt
commands =
    coverage run --rcfile={toxinidir}/tox.ini --source=relatorio --omit=*/tests/* -m xmlrunner discover -s relatorio.tests {posargs}
commands_post =
    coverage report --rcfile={toxinidir}/tox.ini
    coverage xml --rcfile={toxinidir}/tox.ini -o {package_root}/coverage.xml
deps =
    coverage
    unittest-xml-reporting
    pyyaml
    pycha
passenv = *

[coverage:run]
relative_files = true
